# Generated by Django 3.1.7 on 2021-03-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenancy_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('number_of_contracts', models.PositiveIntegerField(default=0)),
                ('last_invoice_number', models.PositiveIntegerField()),
                ('day_next_prolong', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('vat_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('percentage', models.FloatField()),
                ('general_ledger_account', models.CharField(max_length=10)),
                ('general_ledger_dimension', models.CharField(max_length=10)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('contract_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=50)),
                ('general_ledger_debit', models.CharField(max_length=10)),
                ('general_ledger_credit', models.CharField(max_length=10)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='BaseComponent',
            fields=[
                ('base_component_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=50)),
                ('general_ledger_debit', models.CharField(max_length=10)),
                ('general_ledger_credit', models.CharField(max_length=10)),
                ('general_ledger_dimension', models.CharField(max_length=10)),
                ('unit_id', models.CharField(max_length=10)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.tenancy')),
            ],
        ),
    ]
