# Generated by Django 3.1.7 on 2021-03-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='last_invoice_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=1)),
                ('invoicing_period', models.CharField(choices=[('M', 'month'), ('Q', 'quarter'), ('H', 'half year'), ('Y', 'year'), ('V', 'custom')], default='M', max_length=1)),
                ('invoicing_amount_type', models.CharField(choices=[('P', 'per period'), ('D', 'per day')], default='P', max_length=1)),
                ('invoicing_amount_of_days', models.PositiveSmallIntegerField(null=True)),
                ('invoicing_start_day', models.PositiveSmallIntegerField(null=True)),
                ('internal_customer_id', models.PositiveIntegerField()),
                ('external_customer_id', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('end_date_prolong', models.DateField()),
                ('next_date_prolong', models.DateField()),
                ('balance', models.FloatField()),
                ('base_amount', models.FloatField()),
                ('vat_amount', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('general_ledger_dimension_contract_1', models.CharField(max_length=10)),
                ('general_ledger_dimension_contract_2', models.CharField(max_length=10)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.contracttype')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.tenancy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('invoicing_period', 'V'), ('invoicing_amount_of_days', True), ('invoicing_start_day', None)), models.Q(('invoicing_period', False), ('invoicing_amount_of_days', None), ('invoicing_start_day', True)), _connector='OR'), name='check_period'),
        ),
    ]
