# Generated by Django 3.1.7 on 2021-03-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0003_auto_20210322_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='invoicing_amount_of_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='invoicing_start_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
