# Generated by Django 3.1.7 on 2021-03-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0005_auto_20210322_1701'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='check_period',
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('invoicing_period', 'V'), ('invoicing_amount_of_days', True), ('invoicing_start_day', None)), models.Q(('invoicing_period', False), ('invoicing_amount_of_days', None), ('invoicing_start_day', True)), _connector='OR'), name='check_period'),
        ),
    ]
