# Generated by Django 3.1.7 on 2021-03-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0006_auto_20210322_1717'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='check_period',
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('invoicing_period', 'V'), ('invoicing_amount_of_days__isnull', False), ('invoicing_start_day__isnull', True)), models.Q(('invoicing_period', 'M'), ('invoicing_amount_of_days__isnull', True), ('invoicing_start_day__isnull', False)), _connector='OR'), name='check_period'),
        ),
    ]
