# Generated by Django 3.1.7 on 2021-03-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0007_auto_20210322_1731'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='check_period',
        ),
        migrations.AlterField(
            model_name='component',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='component',
            name='vat_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('invoicing_period', 'V'), ('invoicing_amount_of_days__isnull', False), ('invoicing_start_day__isnull', True)), models.Q(models.Q(('invoicing_period', 'M'), ('invoicing_period', 'Q'), ('invoicing_period', 'H'), ('invoicing_period', 'Y'), _connector='OR'), ('invoicing_amount_of_days__isnull', True), ('invoicing_start_day__isnull', False)), _connector='OR'), name='check_period'),
        ),
    ]
