# Generated by Django 3.1.7 on 2021-03-25 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0008_auto_20210322_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPerson',
            fields=[
                ('contract_person_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[(1, 'ai'), (2, 'email'), (3, 'sms'), (4, 'letter'), (5, 'invoice')], default=5, max_length=1)),
                ('iban', models.CharField(max_length=17)),
                ('mandate', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('percentage_of_total', models.PositiveIntegerField()),
                ('payment_day', models.PositiveIntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.contract')),
            ],
        ),
    ]
