# Generated by Django 3.1.7 on 2021-04-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0010_auto_20210327_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tenancy',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.tenancy'),
            preserve_default=False,
        ),
    ]
