# Generated by Django 3.1.7 on 2021-04-03 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0012_component_tenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractperson',
            name='tenancy',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.tenancy'),
            preserve_default=False,
        ),
    ]
