# Generated by Django 3.1.7 on 2021-04-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0014_auto_20210405_1513'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='component',
            name='component_start_before_end',
        ),
        migrations.RemoveConstraint(
            model_name='contract',
            name='contract_start_before_end',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='invoice_number',
            new_name='number_of_units',
        ),
        migrations.AlterField(
            model_name='component',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vatrate',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
