# Generated by Django 3.1.7 on 2021-04-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0015_auto_20210405_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vatrate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
