# Generated by Django 3.1.7 on 2021-04-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0016_auto_20210405_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='base_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='end_date_prolong',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='number_of_units',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='unit_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='unit_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date_prolong',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='base_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.contract'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.component'),
        ),
    ]
