# Generated by Django 3.1.7 on 2021-04-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0017_auto_20210407_1434'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='check_period',
        ),
    ]
