# Generated by Django 3.1.7 on 2021-04-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0018_auto_20210407_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='base_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='number_of_units',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unit_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
    ]
