# Generated by Django 3.1.7 on 2021-04-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0019_auto_20210407_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractperson',
            name='payment_method',
            field=models.CharField(choices=[('D', 'direct debit'), ('E', 'email'), ('S', 'sms'), ('L', 'letter'), ('I', 'invoice')], default='I', max_length=1),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=1)),
                ('payment_day', models.PositiveIntegerField()),
                ('mandate', models.PositiveIntegerField()),
                ('iban', models.CharField(max_length=17)),
                ('amount', models.FloatField()),
                ('contract_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.contractperson')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.invoice')),
            ],
        ),
    ]
