# Generated by Django 3.1.7 on 2021-04-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0020_auto_20210415_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='last_invoice_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='GeneralLedgerPost',
            fields=[
                ('general_ledger_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('general_ledger_account', models.CharField(max_length=10)),
                ('general_ledger_dimension_base_component', models.CharField(max_length=10)),
                ('general_ledger_dimension_contract_1', models.CharField(max_length=10)),
                ('general_ledger_dimension_contract_2', models.CharField(max_length=10)),
                ('general_ledger_dimension_vat', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=30)),
                ('amount_debit', models.FloatField()),
                ('amount_credit', models.FloatField()),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.invoice')),
                ('invoice_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.invoiceline')),
            ],
        ),
    ]
