# Generated by Django 3.1.7 on 2021-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0021_auto_20210416_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgerpost',
            name='general_ledger_dimension_base_component',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='generalledgerpost',
            name='general_ledger_dimension_vat',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
