# Generated by Django 3.1.7 on 2021-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0022_auto_20210416_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='base_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='number_of_units',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='unit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='unit_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
