# Generated by Django 3.1.7 on 2021-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0023_auto_20210419_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractperson',
            name='iban',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='mandate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
