# Generated by Django 3.1.7 on 2021-04-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0024_auto_20210419_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecomponent',
            name='unit_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
