# Generated by Django 3.1.7 on 2021-04-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0025_auto_20210419_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='internal_customer_id',
        ),
    ]
