# Generated by Django 3.1.7 on 2021-04-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0026_remove_invoice_internal_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='internal_customer_id',
        ),
    ]
