# Generated by Django 3.1.7 on 2021-04-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0027_remove_contract_internal_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='day_next_prolong',
            field=models.DateField(blank=True, null=True),
        ),
    ]
