# Generated by Django 3.1.7 on 2021-04-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0023_auto_20210427_0613'),
        ('InvoiceEngineApp', '0028_auto_20210426_1249'),
    ]

    operations = [
    ]
