# Generated by Django 3.1.7 on 2021-04-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0029_merge_20210427_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tenancy',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.tenancy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalledgerpost',
            name='tenancy',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.tenancy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='invoicing_period',
            field=models.CharField(choices=[('M', 'Month'), ('Q', 'Quarter'), ('H', 'Half year'), ('Y', 'Year'), ('V', 'Custom')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='percentage_of_total',
            field=models.PositiveIntegerField(),
        ),
    ]
