# Generated by Django 3.1.7 on 2021-04-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0032_auto_20210430_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_id',
        ),
        migrations.RemoveField(
            model_name='generalledgerpost',
            name='general_ledger_post_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice_line_id',
        ),
        migrations.AddField(
            model_name='collection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalledgerpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
