# Generated by Django 3.1.7 on 2021-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0034_auto_20210430_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice_line_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
