# Generated by Django 3.1.7 on 2021-05-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0036_auto_20210501_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_next_prolongation',
            field=models.DateField(null=True),
        ),
    ]
