# Generated by Django 3.1.7 on 2021-05-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0037_auto_20210502_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecomponent',
            old_name='general_ledger_credit',
            new_name='gl_credit',
        ),
        migrations.RenameField(
            model_name='basecomponent',
            old_name='general_ledger_debit',
            new_name='gl_debit',
        ),
        migrations.RenameField(
            model_name='basecomponent',
            old_name='general_ledger_dimension',
            new_name='gl_dimension',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='general_ledger_dimension_contract_1',
            new_name='gl_dimension_1',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='general_ledger_dimension_contract_2',
            new_name='gl_dimension_2',
        ),
        migrations.RenameField(
            model_name='contracttype',
            old_name='general_ledger_credit',
            new_name='gl_credit',
        ),
        migrations.RenameField(
            model_name='contracttype',
            old_name='general_ledger_debit',
            new_name='gl_debit',
        ),
        migrations.RenameField(
            model_name='generalledgerpost',
            old_name='general_ledger_account',
            new_name='gl_account',
        ),
        migrations.RenameField(
            model_name='generalledgerpost',
            old_name='general_ledger_dimension_base_component',
            new_name='gl_dimension_base_component',
        ),
        migrations.RenameField(
            model_name='generalledgerpost',
            old_name='general_ledger_dimension_contract_1',
            new_name='gl_dimension_contract_1',
        ),
        migrations.RenameField(
            model_name='generalledgerpost',
            old_name='general_ledger_dimension_contract_2',
            new_name='gl_dimension_contract_2',
        ),
        migrations.RenameField(
            model_name='generalledgerpost',
            old_name='general_ledger_dimension_vat',
            new_name='gl_dimension_vat',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='general_ledger_account',
            new_name='gl_account',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='general_ledger_account',
            new_name='gl_account',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='general_ledger_dimension_base_component',
            new_name='gl_dimension_base_component',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='general_ledger_dimension_contract_1',
            new_name='gl_dimension_contract_1',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='general_ledger_dimension_contract_2',
            new_name='gl_dimension_contract_2',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='general_ledger_dimension_vat',
            new_name='gl_dimension_vat',
        ),
        migrations.RenameField(
            model_name='vatrate',
            old_name='general_ledger_account',
            new_name='gl_account',
        ),
        migrations.RenameField(
            model_name='vatrate',
            old_name='general_ledger_dimension',
            new_name='gl_dimension',
        ),
    ]
