# Generated by Django 3.1.7 on 2021-05-10 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0038_auto_20210507_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='date_prolonged_until',
            new_name='date_prev_prolongation',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='date_prolonged_until',
            new_name='date_prev_prolongation',
        ),
        migrations.AddField(
            model_name='vatrate',
            name='successor_vat_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.vatrate'),
        ),
    ]
