# Generated by Django 3.1.7 on 2021-05-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0039_auto_20210510_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_prev_prolongation',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vatrate',
            name='successor_vat_rate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvoiceEngineApp.vatrate'),
        ),
    ]
