# Generated by Django 3.1.7 on 2021-05-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0040_auto_20210513_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='invoicing_amount_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='invoicing_start_day',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.AlterField(
            model_name='component',
            name='date_prev_prolongation',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_next_prolongation',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
