# Generated by Django 3.1.7 on 2021-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0041_auto_20210515_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractperson',
            name='phone',
            field=models.CharField(default='0612345678', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
