# Generated by Django 3.1.7 on 2021-05-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0042_auto_20210515_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InvoiceEngineApp.vatrate'),
        ),
    ]
