# Generated by Django 3.1.7 on 2021-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0043_auto_20210515_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='iban',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='mandate',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
