# Generated by Django 3.1.7 on 2021-05-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0044_auto_20210515_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('F', 'Draft'), ('A', 'Active'), ('T', 'Terminated'), ('E', 'Ended'), ('H', 'Historic')], default='F', max_length=1),
        ),
    ]
