# Generated by Django 3.1.7 on 2021-05-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0045_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractperson',
            name='address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='city',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='iban',
            field=models.CharField(blank=True, default=None, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='mandate',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='payment_day',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='percentage_of_total',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contractperson',
            name='type',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
