# Generated by Django 3.1.7 on 2021-05-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0046_auto_20210516_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvoiceEngineApp.vatrate'),
        ),
    ]
