# Generated by Django 3.1.7 on 2021-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0048_auto_20210517_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
