# Generated by Django 3.1.7 on 2021-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0049_contract_termination_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttype',
            name='type',
        ),
    ]
