# Generated by Django 3.1.7 on 2022-11-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceEngineApp', '0054_contract_pricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractperson',
            name='payment_day',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
